package br.com.dynamic.entidade;

// Generated 08/10/2014 05:47:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AtendimentoId generated by hbm2java
 */
@Embeddable
public class AtendimentoId implements java.io.Serializable {

	private int idAtendimento;
	private int usuarioIdUsuario;

	public AtendimentoId() {
	}

	public AtendimentoId(int idAtendimento, int clienteIdCliente,
			int clienteUsuarioIdUsuario, int usuarioIdUsuario) {
		this.idAtendimento = idAtendimento;
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	@Column(name = "idAtendimento", nullable = false)
	public int getIdAtendimento() {
		return this.idAtendimento;
	}

	public void setIdAtendimento(int idAtendimento) {
		this.idAtendimento = idAtendimento;
	}

	@Column(name = "Usuario_idUsuario", nullable = false)
	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AtendimentoId))
			return false;
		AtendimentoId castOther = (AtendimentoId) other;

		return (this.getIdAtendimento() == castOther.getIdAtendimento())
				&& (this.getUsuarioIdUsuario() == castOther
						.getUsuarioIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAtendimento();
		result = 37 * result + this.getUsuarioIdUsuario();
		return result;
	}

}
