package br.com.dynamic.entidade;

// Generated 08/10/2014 05:47:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "energia", uniqueConstraints = @UniqueConstraint(columnNames = "nome,fone"))
public class Cliente implements java.io.Serializable {

	private ClienteId id;
	private Usuario usuario;
	private int idAtendimento;
	private String nome;
	private String fone;
	private String cpf;
	private Date nascimento;
	private String status;
	private String retorno;
	private String renovacao;
	private String fone2;
	private String fone3;
	private Set ordems = new HashSet(0);

	public Cliente() {
	}

	public Cliente(ClienteId id, Usuario usuario, String nome, int idAtendimento) {
		this.id = id;
		this.usuario = usuario;
		this.nome = nome;
		this.idAtendimento = idAtendimento;
	}

	public Cliente(ClienteId id, Usuario usuario, String nome, String fone,
			String cpf, Date nascimento, String status, String retorno,
			String renovacao, String fone2, String fone3, int idAtendimento, Set ordems) {
		this.id = id;
		this.usuario = usuario;
		this.nome = nome;
		this.fone = fone;
		this.cpf = cpf;
		this.nascimento = nascimento;
		this.status = status;
		this.retorno = retorno;
		this.renovacao = renovacao;
		this.fone2 = fone2;
		this.fone3 = fone3;
		this.idAtendimento = idAtendimento;
		this.ordems = ordems;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCliente", column = @Column(name = "idCliente", nullable = false)),
			@AttributeOverride(name = "usuarioIdUsuario", column = @Column(name = "Usuario_idUsuario", nullable = false)) })
	public ClienteId getId() {
		return this.id;
	}

	public void setId(ClienteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Usuario_idUsuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nome", unique = true, nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "fone", length = 20)
	public String getFone() {
		return this.fone;
	}

	public void setFone(String fone) {
		this.fone = fone;
	}

	@Column(name = "cpf", length = 20)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "nascimento", length = 10)
	public Date getNascimento() {
		return this.nascimento;
	}

	public void setNascimento(Date nascimento) {
		this.nascimento = nascimento;
	}

	@Column(name = "status", length = 30)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "retorno", length = 50)
	public String getRetorno() {
		return this.retorno;
	}

	public void setRetorno(String retorno) {
		this.retorno = retorno;
	}

	@Column(name = "renovacao", length = 50)
	public String getRenovacao() {
		return this.renovacao;
	}

	public void setRenovacao(String renovacao) {
		this.renovacao = renovacao;
	}

	@Column(name = "fone2", length = 50)
	public String getFone2() {
		return this.fone2;
	}

	public void setFone2(String fone2) {
		this.fone2 = fone2;
	}

	@Column(name = "fone3", length = 11)
	public String getFone3() {
		return this.fone3;
	}

	public void setFone3(String fone3) {
		this.fone3 = fone3;
	}
	
	@Column(name = "atendimento_idAtendimento")
	public int getIdAtendimento() {
		return this.idAtendimento;
	}

	public void setIdAtendimento(int idAtendimento) {
		this.idAtendimento = idAtendimento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set getOrdems() {
		return this.ordems;
	}

	public void setOrdems(Set ordems) {
		this.ordems = ordems;
	}

}
