package br.com.dynamic.entidade;

// Generated 08/10/2014 05:47:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClienteId generated by hbm2java
 */
@Embeddable
public class ClienteId implements java.io.Serializable {

	private int idCliente;
	private int usuarioIdUsuario;

	public ClienteId() {
	}

	public ClienteId(int idCliente, int usuarioIdUsuario) {
		this.idCliente = idCliente;
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	@Column(name = "idCliente", nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "Usuario_idUsuario", nullable = false)
	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteId))
			return false;
		ClienteId castOther = (ClienteId) other;

		return (this.getIdCliente() == castOther.getIdCliente())
				&& (this.getUsuarioIdUsuario() == castOther
						.getUsuarioIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCliente();
		result = 37 * result + this.getUsuarioIdUsuario();
		return result;
	}

}
