package br.com.dynamic.entidade;

// Generated 08/10/2014 05:47:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FuncionarioId generated by hbm2java
 */
@Embeddable
public class FuncionarioId implements java.io.Serializable {

	private int idFuncionario;
	private int usuarioIdUsuario;

	public FuncionarioId() {
	}

	public FuncionarioId(int idFuncionario, int usuarioIdUsuario) {
		this.idFuncionario = idFuncionario;
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	@Column(name = "idFuncionario", nullable = false)
	public int getIdFuncionario() {
		return this.idFuncionario;
	}

	public void setIdFuncionario(int idFuncionario) {
		this.idFuncionario = idFuncionario;
	}

	@Column(name = "Usuario_idUsuario", nullable = false)
	public int getUsuarioIdUsuario() {
		return this.usuarioIdUsuario;
	}

	public void setUsuarioIdUsuario(int usuarioIdUsuario) {
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FuncionarioId))
			return false;
		FuncionarioId castOther = (FuncionarioId) other;

		return (this.getIdFuncionario() == castOther.getIdFuncionario())
				&& (this.getUsuarioIdUsuario() == castOther
						.getUsuarioIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFuncionario();
		result = 37 * result + this.getUsuarioIdUsuario();
		return result;
	}

}
