package br.com.dynamic.entidade;

// Generated 08/10/2014 05:47:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdemId generated by hbm2java
 */
@Embeddable
public class OrdemId implements java.io.Serializable {

	private int idOrdem;
	private int funcionarioIdFuncionario;
	private int funcionarioUsuarioIdUsuario;
	private int clienteIdCliente;
	private int clienteUsuarioIdUsuario;

	public OrdemId() {
	}

	public OrdemId(int idOrdem, int funcionarioIdFuncionario,
			int funcionarioUsuarioIdUsuario, int clienteIdCliente,
			int clienteUsuarioIdUsuario) {
		this.idOrdem = idOrdem;
		this.funcionarioIdFuncionario = funcionarioIdFuncionario;
		this.funcionarioUsuarioIdUsuario = funcionarioUsuarioIdUsuario;
		this.clienteIdCliente = clienteIdCliente;
		this.clienteUsuarioIdUsuario = clienteUsuarioIdUsuario;
	}

	@Column(name = "idOrdem", nullable = false)
	public int getIdOrdem() {
		return this.idOrdem;
	}

	public void setIdOrdem(int idOrdem) {
		this.idOrdem = idOrdem;
	}

	@Column(name = "Funcionario_idFuncionario", nullable = false)
	public int getFuncionarioIdFuncionario() {
		return this.funcionarioIdFuncionario;
	}

	public void setFuncionarioIdFuncionario(int funcionarioIdFuncionario) {
		this.funcionarioIdFuncionario = funcionarioIdFuncionario;
	}

	@Column(name = "Funcionario_Usuario_idUsuario", nullable = false)
	public int getFuncionarioUsuarioIdUsuario() {
		return this.funcionarioUsuarioIdUsuario;
	}

	public void setFuncionarioUsuarioIdUsuario(int funcionarioUsuarioIdUsuario) {
		this.funcionarioUsuarioIdUsuario = funcionarioUsuarioIdUsuario;
	}

	@Column(name = "Cliente_idCliente", nullable = false)
	public int getClienteIdCliente() {
		return this.clienteIdCliente;
	}

	public void setClienteIdCliente(int clienteIdCliente) {
		this.clienteIdCliente = clienteIdCliente;
	}

	@Column(name = "Cliente_Usuario_idUsuario", nullable = false)
	public int getClienteUsuarioIdUsuario() {
		return this.clienteUsuarioIdUsuario;
	}

	public void setClienteUsuarioIdUsuario(int clienteUsuarioIdUsuario) {
		this.clienteUsuarioIdUsuario = clienteUsuarioIdUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdemId))
			return false;
		OrdemId castOther = (OrdemId) other;

		return (this.getIdOrdem() == castOther.getIdOrdem())
				&& (this.getFuncionarioIdFuncionario() == castOther
						.getFuncionarioIdFuncionario())
				&& (this.getFuncionarioUsuarioIdUsuario() == castOther
						.getFuncionarioUsuarioIdUsuario())
				&& (this.getClienteIdCliente() == castOther
						.getClienteIdCliente())
				&& (this.getClienteUsuarioIdUsuario() == castOther
						.getClienteUsuarioIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrdem();
		result = 37 * result + this.getFuncionarioIdFuncionario();
		result = 37 * result + this.getFuncionarioUsuarioIdUsuario();
		result = 37 * result + this.getClienteIdCliente();
		result = 37 * result + this.getClienteUsuarioIdUsuario();
		return result;
	}

}
